package de.hahn.blog.accessresourcesfrompath.model.facade.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 01 14:01:18 CEST 2012
// ---------------------------------------------------------------------
public interface BARFPAppModule extends ApplicationModule {
    String getModelResource(String key);
}
