package de.hahn.blog.accessresourcesfrompath.model.facade.client;

import de.hahn.blog.accessresourcesfrompath.model.facade.common.BARFPAppModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 01 14:01:18 CEST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BARFPAppModuleClient extends ApplicationModuleImpl implements BARFPAppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public BARFPAppModuleClient() {
    }

    public String getModelResource(String key) {
        Object _ret =
            this.riInvokeExportedMethod(this,"getModelResource",new String [] {"java.lang.String"},new Object[] {key});
        return (String)_ret;
    }
}
